# Generated by Django 2.2 on 2019-07-21 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brief', models.CharField(blank=True, max_length=255, null=True)),
                ('max_members', models.IntegerField(default=200)),
                ('admins', models.ManyToManyField(blank=True, related_name='group_admins', to='bbs.UserProfile')),
                ('members', models.ManyToManyField(blank=True, related_name='group_members', to='bbs.UserProfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile')),
            ],
            options={
                'verbose_name': '聊天组',
                'verbose_name_plural': '聊天组',
            },
        ),
    ]
