# Generated by Django 2.2 on 2019-07-21 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('head_img', models.ImageField(upload_to='uploads', verbose_name='文章标题图片')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('last_modify', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('priority', models.IntegerField(default=1000, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '隐藏')], default='published', max_length=64)),
            ],
            options={
                'verbose_name': '帖子表',
                'verbose_name_plural': '帖子表',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='昵称')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='签名')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='头像')),
                ('friends', models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='bbs.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联Django内部的用户')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.IntegerField(choices=[(1, '评论'), (2, '点赞')], default=1, verbose_name='评论类型')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Article', verbose_name='所属文章')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_clildren', to='bbs.Comment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile', verbose_name='评论人')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='板块名称')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('set_as_top_menu', models.BooleanField(default=False, verbose_name='是否将此板块设置在页面顶部')),
                ('positon_index', models.SmallIntegerField(verbose_name='顶部展示的位置')),
                ('admins', models.ManyToManyField(blank=True, to='bbs.UserProfile', verbose_name='版主')),
            ],
            options={
                'verbose_name': '板块表',
                'verbose_name_plural': '板块表',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Category', verbose_name='所属板块'),
        ),
    ]
